import Head from 'next/head';
import Image from 'next/image';
import Footer from '../../components/Footer';
import Header from '../../components/Header';
import Nav from '../../components/Nav';
import Results from '../../components/Results';
import request from '../../utils/request';

export default function Home({results,page,total_pages,genre}) {
  // console.log(genre);
  return (
    <>
      <Head>
        <title>Kulu 5.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" />
      </Head>
      <main>
        {/* Header */}
        <Header />
        {/* NAv */}
        <Nav/>
        {/* Results */}
        {/* {console.log(results,page,total_pages)} */}
        <Results movies={results} page={page} total_pages={total_pages} genre={genre}/>
        {/* footer */}
        <Footer/>
      </main>
    </>
  );
}

// sever-side props
export async function getServerSideProps(context)
{
  const genre=context.query.genre;
  const page=context.query.page;
  const req=await fetch(`https://api.themoviedb.org/3${request[genre]?.url || request.fetchTrending.url}&page=${page==null?1:page}`)
  .then(res=>res.json())
  // for trending movies, we get a url https://api.themoviedb.org/3/trending/all/week?api_key=3b4b0d6c9602439b1ed6b6c536bc9f14&language=en-US
  return {
    props: {
      results:req.results,
      page: req.page,
      total_pages: req.total_pages,
      genre: genre==undefined?'fetchTrending':genre
    }
  }
}
